#pragma config(Sensor, dgtl2,  ,               sensorSONAR_cm)
#pragma config(Sensor, dgtl4,  ,               sensorSONAR_cm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(1){
		SensorType[dgtl2] = sensorNone;
		SensorValue[dgtl2];
		SensorType[dgtl4] = sensorSONAR_TwoPins_cm;
		SensorValue[dgtl4];
	}
}
