#pragma config(Sensor, dgtl2,  ,               sensorSONAR_cm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	motor[port3] = 50;
	motor[port2] = -50;

	while(SensorValue(dgtl2) > 10){}
}
