#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,            ,             tmotorVex269_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <GLOBAL2.h>

#define trc 35.0
#define dia 10.16
#define fix 1


task main(){
	nMotorEncoder[port2] = 0;
	nMotorEncoder[port3] = 0;
	/*MoveDist(-61,100,dia);
	motor[port6] = 100;
	wait1Msec(500);
	motor[port6] = 0;
	TurnRobot(90,100,dia,trc,fix);
	MoveDist(-67,100,dia);
	motor[port7] = -100;
	wait1Msec(500);
	motor[port7] = 0;
	MoveDist(63,100,dia);
	TurnRobot(90,100,dia,trc,fix);
	MoveDist(-65,100,dia);
	MoveDist(10,100,dia);*/
	MoveDist(-8,100,dia);
	motor[port7] = -100;
	motor[port6] = 90;
	wait1Msec(500);
	motor[port7] = 0;
	motor[port6] = -10;
	TurnRobot(-34,100,dia,trc,fix);
	for(int i=0; i < 2; i++){
		motor[port4] = -100;
		motor[port5] = 100;
		motor[port6] = 30;
		wait1Msec(600);
		motor[port4] = 0;
		motor[port5] = 0;
		motor[port6] = 0;
		motor[port7] = 100;
		wait1Msec(300);
		motor[port7] = 20;
		wait1Msec(300);
		motor[port4] = -100;
		motor[port5] = 100;
		motor[port6] = 20;
		motor[port2] = -50;
		motor[port3] = -50;
		wait1Msec(800);
		motor[port2] = 50;
		motor[port3] = 50;
		motor[port4] = 0;
		motor[port5] = 0;
		motor[port6] = 0;
		wait1Msec(0);
		TurnRobot(-73,50,dia,trc,fix);
		motor[port2] = 45;
		motor[port3] = 45;
		wait1Msec(100);
		motor[port4] = 100;
		motor[port5] = -100;
		motor[port6] = -105;
		wait1Msec(1000-800*i);
		motor[port4] = -20;
		motor[port5] = 20;
		motor[port6] = 0;
		motor[port7] = -100;
		motor[port2] = 0;
		motor[port3] = 0;
		wait1Msec(1000);
		motor[port7] = 0;
		TurnRobot(90,100,dia,trc,fix);

	}
}
